### ISSUE TITLE
ImportError: No module named _sysconfigdata_nd

### ISSUE THREAD

**Issue by mozmorris** [keiko713/heroku-buildpack-gdb#1]
Hello @keiko713. Any chance you might be able to help with the following?

This is the output after I `heroku run bash` and then `gdb`. 

```
~ $ gdb
Traceback (most recent call last):
  File "/usr/lib/python2.7/site.py", line 563, in <module>
    main()
  File "/usr/lib/python2.7/site.py", line 545, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python2.7/site.py", line 272, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/lib/python2.7/site.py", line 247, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/lib/python2.7/site.py", line 237, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/lib/python2.7/sysconfig.py", line 578, in get_config_var
    return get_config_vars().get(name)
  File "/usr/lib/python2.7/sysconfig.py", line 524, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/usr/lib/python2.7/sysconfig.py", line 408, in _init_posix
    from _sysconfigdata import build_time_vars
  File "/usr/lib/python2.7/_sysconfigdata.py", line 6, in <module>
    from _sysconfigdata_nd import *
ImportError: No module named _sysconfigdata_nd
```

**Comment by keiko713** [comment]
Hi @MozMorris ! Could you please tell me following?
- Which stack are you using? cedar or cedar-14? You can check it with `heroku info -a appname`
- Which buildpack you're using together? In my example, it's Ruby buildpack but are you using something else?

Maybe I can start replicating the issue using above info and dig into deeper.

**Comment by mozmorris** [comment]
I'm using `cedar-14` and Heroku's php buildpack: https://github.com/heroku/heroku-buildpack-php

**Comment by keiko713** [comment]
Hi @MozMorris ! Sorry for taking so loooong time for this, but I built gdb for cedar-14 stack and made a change #2 . Please let me know if it still doesn't work.

**Comment by mozmorris** [comment]
Spot on, thank you!
